apiVersion: v1
kind: Secret
metadata:
  name: github-webhook
  namespace: argocd
stringData:
  github.secret: testsecret  # Replace with the secret you created in GitHub
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.github: |
    webhook:
      url: https://192.168.1.101/api/webhook
      headers:
        - name: Content-Type
          value: application/json 